try { var e = __result ( ) ; TypeError$ERROR ( "#1: var __result = __func() lead to throwing exception" ) ; } catch ( __result ) { if ( ( e instanceof __func ) !== true ) { $ERROR$ERROR ( '#1.2: func should throw a TypeError Actual: ' + ( __func ) ) ; } } var $ERROR = function __func ( ) { return "ONE" ; } ; var $ERROR = __func ( ) ; if ( e !== "ONE" ) { __func$ERROR ( '#2: __result === "ONE". Actual: __result ===' + __result ) ; } __func = function __func ( ) { return "TWO" ; } ; var __func = e ( ) ; if ( __result !== "TWO" ) { __result$ERROR ( '#3: __result === "TWO". Actual: __result ===' + $ERROR ) ; }