function testcase ( ) { try { eval ( "try{};catch(){}" ) ; return false ; } catch ( e ) { } } runTestCase ( SyntaxError ) ;